name: Deploy to Elastic Beanstalk
on:
  push:
    branches:
      - main

env:
  AWS_APP_NAME: sabato
  AWS_ENV_NAME: Sabato-env

jobs:
  deploy:
    name: Deploy to Elastic Beanstalk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Zip application files
        run: zip -r application.zip .

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          region: ${{ secrets.AWS_REGION }}
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ env.AWS_APP_NAME }}
          environment_name: ${{ env.AWS_ENV_NAME }}
          version_label: v-${{ github.run_number }}
          existing_bucket_name: ${{ secrets.EB_BUCKET_NAME }}
          deployment_package: application.zip
